server:
  port: 8080
  servlet:
    session:
      cookie:
        name: TSESSION
        http-only: true #decide if front-end cannot have the access to token (true=cannot)
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/dbSpring17
    username: postgres
    password: Mikolaj8
    driverClassName: org.postgresql.Driver