spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/dbSpring17
    username: postgres
    password: Mikolaj8
    driverClassName: org.postgresql.Driver